FROM alpine:latest

RUN apk update && \
    apk add openjdk17-jdk

ENV JAVA_HOME=/usr/lib/jvm/default-jvm
ENV SPARK_HOME=/usr/lib/python3.12/site-packages/pyspark

RUN apk add bash && \
  apk add nano && \
  apk add postgresql-client && \
  apk add --update  python3 py3-pip  && \
  pip3 install pyspark  --break-system-packages --root-user-action=ignore && \
  pip3 install pytest  --break-system-packages --root-user-action=ignore

RUN apk add build-base
RUN apk add python3-dev
RUN apk add musl-dev
RUN apk add linux-headers
RUN apk add libffi-dev
RUN apk add openblas-dev
RUN apk add zlib-dev
RUN apk add jpeg-dev
RUN apk add zeromq-dev
RUN pip3 install --upgrade setuptools wheel --break-system-packages --root-user-action=ignore
RUN pip3 install numpy --break-system-packages --root-user-action=ignore
RUN pip3 install matplotlib --break-system-packages --root-user-action=ignore
RUN pip3 install seaborn --break-system-packages --root-user-action=ignore
RUN pip3 install notebook --break-system-packages --root-user-action=ignore
RUN pip3 install findspark --break-system-packages --root-user-action=ignore

WORKDIR /src

COPY . /src
